-- ==============================================================================
-- SUPABASE DATABASE SCHEMA FOR FAMILY DIARY (MEDIA TABLE)
-- Run this script in your Supabase Project -> SQL Editor
-- ==============================================================================

-- 1. Create table for media entries (photos and videos)
create table if not exists public.media (
  id bigint generated by default as identity primary key,
  title text not null default '',
  storage_path text not null unique,
  url text not null,
  type text not null default 'image', -- 'image' or 'video'
  width integer default 720,
  height integer default 480,
  blur_data_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. Create index on created_at for fast timeline sorting
create index if not exists idx_media_created_at on public.media (created_at desc);

-- 3. Enable Row Level Security (RLS)
alter table public.media enable row level security;

-- 4. Create RLS Policies
-- Allow anyone (public, visitors) to view media entries
drop policy if exists "Public Select Media" on public.media;
create policy "Public Select Media"
  on public.media
  for select
  to public
  using (true);

-- Only authenticated users (Admin) can insert new media
drop policy if exists "Admin Insert Media" on public.media;
create policy "Admin Insert Media"
  on public.media
  for insert
  to authenticated
  with check (true);

-- Only authenticated users (Admin) can update media entries
drop policy if exists "Admin Update Media" on public.media;
create policy "Admin Update Media"
  on public.media
  for update
  to authenticated
  using (true);

-- Only authenticated users (Admin) can delete media entries
drop policy if exists "Admin Delete Media" on public.media;
create policy "Admin Delete Media"
  on public.media
  for delete
  to authenticated
  using (true);
